# Generated by Django 3.2.9 on 2022-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
    ]
